// source: restaurant_group.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var basic_pb = require('./basic_pb.js');
goog.object.extend(proto, basic_pb);
var restaurant_pb = require('./restaurant_pb.js');
goog.object.extend(proto, restaurant_pb);
goog.exportSymbol('proto.restaurant.RestaurantGroup', null, global);
goog.exportSymbol('proto.restaurant.RestaurantGroup.Contact', null, global);
goog.exportSymbol('proto.restaurant.RestaurantGroupType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.restaurant.RestaurantGroup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.restaurant.RestaurantGroup.repeatedFields_, null);
};
goog.inherits(proto.restaurant.RestaurantGroup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.restaurant.RestaurantGroup.displayName = 'proto.restaurant.RestaurantGroup';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.restaurant.RestaurantGroup.Contact = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.restaurant.RestaurantGroup.Contact, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.restaurant.RestaurantGroup.Contact.displayName = 'proto.restaurant.RestaurantGroup.Contact';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.restaurant.RestaurantGroup.repeatedFields_ = [5,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.restaurant.RestaurantGroup.prototype.toObject = function(opt_includeInstance) {
  return proto.restaurant.RestaurantGroup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.restaurant.RestaurantGroup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.restaurant.RestaurantGroup.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    username: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hasword: jspb.Message.getFieldWithDefault(msg, 3, ""),
    hashwordSalt: jspb.Message.getFieldWithDefault(msg, 4, 0),
    contactsList: jspb.Message.toObjectList(msg.getContactsList(),
    proto.restaurant.RestaurantGroup.Contact.toObject, includeInstance),
    personOfContact: jspb.Message.getFieldWithDefault(msg, 6, ""),
    restaurantsList: jspb.Message.toObjectList(msg.getRestaurantsList(),
    basic_pb.RestId.toObject, includeInstance),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.restaurant.RestaurantGroup}
 */
proto.restaurant.RestaurantGroup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.restaurant.RestaurantGroup;
  return proto.restaurant.RestaurantGroup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.restaurant.RestaurantGroup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.restaurant.RestaurantGroup}
 */
proto.restaurant.RestaurantGroup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHasword(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHashwordSalt(value);
      break;
    case 5:
      var value = new proto.restaurant.RestaurantGroup.Contact;
      reader.readMessage(value,proto.restaurant.RestaurantGroup.Contact.deserializeBinaryFromReader);
      msg.addContacts(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPersonOfContact(value);
      break;
    case 7:
      var value = new basic_pb.RestId;
      reader.readMessage(value,basic_pb.RestId.deserializeBinaryFromReader);
      msg.addRestaurants(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.restaurant.RestaurantGroup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.restaurant.RestaurantGroup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.restaurant.RestaurantGroup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.restaurant.RestaurantGroup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHasword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHashwordSalt();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getContactsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.restaurant.RestaurantGroup.Contact.serializeBinaryToWriter
    );
  }
  f = message.getPersonOfContact();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRestaurantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      basic_pb.RestId.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.restaurant.RestaurantGroup.Contact.prototype.toObject = function(opt_includeInstance) {
  return proto.restaurant.RestaurantGroup.Contact.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.restaurant.RestaurantGroup.Contact} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.restaurant.RestaurantGroup.Contact.toObject = function(includeInstance, msg) {
  var f, obj = {
    phoneNumber: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.restaurant.RestaurantGroup.Contact}
 */
proto.restaurant.RestaurantGroup.Contact.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.restaurant.RestaurantGroup.Contact;
  return proto.restaurant.RestaurantGroup.Contact.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.restaurant.RestaurantGroup.Contact} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.restaurant.RestaurantGroup.Contact}
 */
proto.restaurant.RestaurantGroup.Contact.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoneNumber(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.restaurant.RestaurantGroup.Contact.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.restaurant.RestaurantGroup.Contact.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.restaurant.RestaurantGroup.Contact} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.restaurant.RestaurantGroup.Contact.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string phone_number = 1;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.Contact.prototype.getPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup.Contact} returns this
 */
proto.restaurant.RestaurantGroup.Contact.prototype.setPhoneNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.Contact.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup.Contact} returns this
 */
proto.restaurant.RestaurantGroup.Contact.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.Contact.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup.Contact} returns this
 */
proto.restaurant.RestaurantGroup.Contact.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string username = 2;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string hasword = 3;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.prototype.getHasword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.setHasword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 hashword_salt = 4;
 * @return {number}
 */
proto.restaurant.RestaurantGroup.prototype.getHashwordSalt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.setHashwordSalt = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated Contact contacts = 5;
 * @return {!Array<!proto.restaurant.RestaurantGroup.Contact>}
 */
proto.restaurant.RestaurantGroup.prototype.getContactsList = function() {
  return /** @type{!Array<!proto.restaurant.RestaurantGroup.Contact>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.restaurant.RestaurantGroup.Contact, 5));
};


/**
 * @param {!Array<!proto.restaurant.RestaurantGroup.Contact>} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
*/
proto.restaurant.RestaurantGroup.prototype.setContactsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.restaurant.RestaurantGroup.Contact=} opt_value
 * @param {number=} opt_index
 * @return {!proto.restaurant.RestaurantGroup.Contact}
 */
proto.restaurant.RestaurantGroup.prototype.addContacts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.restaurant.RestaurantGroup.Contact, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.clearContactsList = function() {
  return this.setContactsList([]);
};


/**
 * optional string person_of_contact = 6;
 * @return {string}
 */
proto.restaurant.RestaurantGroup.prototype.getPersonOfContact = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.setPersonOfContact = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated RestId restaurants = 7;
 * @return {!Array<!proto.restaurant.RestId>}
 */
proto.restaurant.RestaurantGroup.prototype.getRestaurantsList = function() {
  return /** @type{!Array<!proto.restaurant.RestId>} */ (
    jspb.Message.getRepeatedWrapperField(this, basic_pb.RestId, 7));
};


/**
 * @param {!Array<!proto.restaurant.RestId>} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
*/
proto.restaurant.RestaurantGroup.prototype.setRestaurantsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.restaurant.RestId=} opt_value
 * @param {number=} opt_index
 * @return {!proto.restaurant.RestId}
 */
proto.restaurant.RestaurantGroup.prototype.addRestaurants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.restaurant.RestId, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.clearRestaurantsList = function() {
  return this.setRestaurantsList([]);
};


/**
 * optional google.protobuf.Timestamp created_at = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.restaurant.RestaurantGroup.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
*/
proto.restaurant.RestaurantGroup.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.restaurant.RestaurantGroup.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.restaurant.RestaurantGroup.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.restaurant.RestaurantGroup} returns this
*/
proto.restaurant.RestaurantGroup.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.restaurant.RestaurantGroup} returns this
 */
proto.restaurant.RestaurantGroup.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.restaurant.RestaurantGroup.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * @enum {number}
 */
proto.restaurant.RestaurantGroupType = {
  MALL: 0,
  FRANCHISE: 1
};

goog.object.extend(exports, proto.restaurant);
